alias be='bundle exec'
alias atom='open -a atom'
alias bash_profile='atom ~/.bash_profile'
alias postgre_start='brew services start postgresql'
alias postgre_stop='brew services stop postgresql'
alias postgre_restart='brew services restart postgresql'
alias source_bash_profile='source ~/.bash_profile'

alias go_go_shoryuken='bundle exec shoryuken -R -C config/shoryuken.yml'
alias jupyter_notebook='jupyter notebook'
alias grepi='grep -i'
